### ISSUE TITLE
Scheduler support

### ISSUE THREAD

**Issue by vktor18** [logstash-plugins/logstash-input-elasticsearch#65]
I propose to add this feature using a new parameter `schedule`

**Comment by markwalkom** [comment]
++ to this. We do it for JDBC now so hopefully we can port it over easily (hopefully!).

I've also updated the topic to make the request clearer :)

**Comment by zorbalaras** [comment]
+1

**Comment by okazymyrov** [comment]
+1

**Comment by kabali12345** [comment]
+1

**Comment by okazymyrov** [comment]
The current implementation of logstash-input-elasticsearch is implemented in such a way that logstash restarts each time after completion. Scheduler has to receive a high priority since the start process of logstash is unpredictable and have lots of performance issues (e.g., https://github.com/elastic/logstash/issues/5507).

**Comment by magnusbaeck** [comment]
This looks like a duplicate of #32.

**Comment by ph** [comment]
closing this in favor of #32
